### PR TITLE
Update test + implement correct behaviour for oneOf paths

### PR DESCRIPTION
**Pull request by aychtang**
@RangerMauve: Here is the required update for #2.

### CODE REVIEW

**Comment by aychtang** [comment]
Also the test file doesn't give a very useful error at the moment when failing, do you want me to fix that sometime?

**Comment by RangerMauve** [comment]
Yeah, of course. If you have any ideas about better error messages feel free to send a PR. 😁

**Review by RangerMauve — APPROVED** [review]
LGTM

**Comment by RangerMauve** [comment]
Thanks for the fix! It's out in 2.0.1 😁🎉

**Pull request merged**
